In [1]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl (14.5 MB)
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB 393.8 kB/s eta 0:00:37
   ---------------------------------------- 0.1/14.5 MB 722.1 kB/s eta 0:00:20
    --------------------------------------- 0.3/14.5 MB 1.6 MB/s eta 0:00:09
   --- ------------------------------------ 1.1/14.5 MB 4.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.7/14.5 MB 6.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.4/14.5 MB 7.1 MB/s eta 0:00:02
   ------- -------------------------------- 2.8/14.5 MB 7.6 MB/s eta 0:00:02
   ---------- ----------------------------- 3.7/14.5 MB 8.8 MB/s eta 0:00:02
   ------------ --------------------------- 4.4/14.5 MB 9.5 MB/s eta 0:00:02
   -------------- ------------------------- 5.3/14.5 MB 10.2 MB/s eta 0:00:01
   ---------------- ----------------------- 5.9/14.5 MB 10.4 MB/s eta 0:00:01
   ------------------ --------------------- 6.5/14.5 MB 10.7 MB/s eta 0:00:01
   -------------------- ------------------- 7.5/14.5 MB 11.4 MB/s eta 0:00:01
   ---------------------- ----------------- 8.3/14.5 MB 11.8 MB/s eta 0:00:01
   ------------------------- -------------- 9.2/14.5 MB 12.2 MB/s eta 0:00:01
   --------------------------- ------------ 9.8/14.5 MB 12.3 MB/s eta 0:00:01
   ----------------------------- ---------- 10.7/14.5 MB 16.0 MB/s eta 0:00:01
   ------------------------------- -------- 11.5/14.5 MB 16.0 MB/s eta 0:00:01
   --------------------------------- ------ 12.0/14.5 MB 16.0 MB/s eta 0:00:01
   ---------------------------------- ----- 12.5/14.5 MB 15.6 MB/s eta 0:00:01
   ------------------------------------- -- 13.6/14.5 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------  14.1/14.5 MB 16.0 MB/s eta 0:00:01
   ---------------------------------------  14.4/14.5 MB 16.4 MB/s eta 0:00:01
   ---------------------------------------- 14.5/14.5 MB 15.2 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.4.0

In [1]:
import mysql.connector as dbconnection

In [2]:
Myconnection = print("myconnection")

myconnection

In [12]:
import mysql.connector as dbconnect
myconnection = dbconnect.connect(host='localhost', database='classicmodels', user='root',
password='password')
# Get a cursor
cursor = myconnection.cursor()
SQLQuery ="SELECT ordernumber, SUM(quantityOrdered) AS itemsCount, SUM(priceeach*quantityOrdered) AS total FROM orderdetails GROUP BY ordernumber HAVING total > 1000 AND itemsCount > 600";
# Execute a query
cursor.execute(SQLQuery)
# get all records
records = cursor.fetchall()
print("Total number of rows in table: ", cursor.rowcount)
print("\nPrinting each row")
for row in records:
    print("order number = ", row[0], )
    print("item counts = ", row[1])
    print("total = ", row[2], "\n" )
# Close connection
cursor.close()
myconnection.close()

Total number of rows in table:  22

Printing each row
order number =  10106
item counts =  675
total =  52151.81

order number =  10126
item counts =  617
total =  57131.92

order number =  10135
item counts =  607
total =  55601.84

order number =  10165
item counts =  670
total =  67392.85

order number =  10168
item counts =  642
total =  50743.65

order number =  10204
item counts =  619
total =  58793.53

order number =  10207
item counts =  615
total =  59265.14

order number =  10212
item counts =  612
total =  59830.55

order number =  10222
item counts =  717
total =  56822.65

order number =  10262
item counts =  605
total =  47065.36

order number =  10275
item counts =  601
total =  47924.19

order number =  10310
item counts =  619
total =  61234.67

order number =  10312
item counts =  601
total =  55639.66

order number =  10316
item counts =  623
total =  46788.14

order number =  10332
item counts =  621
total =  47159.11

order number =  10339
item counts =  614
total =  48927.64

order number =  10360
item counts =  620
total =  52166.00

order number =  10373
item counts =  605
total =  46770.52

order number =  10386
item counts =  650
total =  46968.52

order number =  10390
item counts =  603
total =  55902.50

order number =  10398
item counts =  629
total =  46656.94

order number =  10414
item counts =  609
total =  50806.85

In [11]:
conn =dbconnect.connect(host='localhost',
                        database='classicmodels',
                        user='root',
                        password='password',
                        port='3306')
if conn.is_connected():
    print('Successfully Connected to MySQL database')

Successfully Connected to MySQL database

In [9]:
import mysql.connector as dbconnect
from mysql.connector import Error
try:
    myconnection = dbconnect.connect(host='localhost',database='classicmodels',user='root',password='password')
    if myconnection.is_connected():
        print('Successfully Connected to MySQL database')
        cursor = myconnection.cursor()
        SQLQuery ="SELECT ordernumber, SUM(quantityOrdered) AS itemsCount, SUM(priceeach*quantityOrdered) AS total FROM orderdetails GROUP BY ordernumber HAVING total > 1000 AND itemsCount > 600";
        cursor.execute(SQLQuery)
        # get all records
        records = cursor.fetchall()
        print("Total number of rows in table: ", cursor.rowcount)
        print("\nPrinting each row")
        for row in records:
            print("order number = ", row[0], )
            print("item counts = ", row[1])
            print("total = ", row[2], "\n" )
except Error as e:
        print("Error while connecting to Database", e)
finally:
        if myconnection.is_connected():
            cursor.close()
            myconnection.close()
        print("Database connection is closed")

Successfully Connected to MySQL database
Total number of rows in table:  22

Printing each row
order number =  10106
item counts =  675
total =  52151.81

order number =  10126
item counts =  617
total =  57131.92

order number =  10135
item counts =  607
total =  55601.84

order number =  10165
item counts =  670
total =  67392.85

order number =  10168
item counts =  642
total =  50743.65

order number =  10204
item counts =  619
total =  58793.53

order number =  10207
item counts =  615
total =  59265.14

order number =  10212
item counts =  612
total =  59830.55

order number =  10222
item counts =  717
total =  56822.65

order number =  10262
item counts =  605
total =  47065.36

order number =  10275
item counts =  601
total =  47924.19

order number =  10310
item counts =  619
total =  61234.67

order number =  10312
item counts =  601
total =  55639.66

order number =  10316
item counts =  623
total =  46788.14

order number =  10332
item counts =  621
total =  47159.11

order number =  10339
item counts =  614
total =  48927.64

order number =  10360
item counts =  620
total =  52166.00

order number =  10373
item counts =  605
total =  46770.52

order number =  10386
item counts =  650
total =  46968.52

order number =  10390
item counts =  603
total =  55902.50

order number =  10398
item counts =  629
total =  46656.94

order number =  10414
item counts =  609
total =  50806.85

Database connection is closed

In [15]:
import mysql.connector
import my_secrets
# Establish a connection to the MySQL server
connection = mysql.connector.connect(
    host="localhost",
    user=my_secrets.mysql_username,
    password=my_secrets.mysql_password,
    database="classicmodels"
)
# Check if the connection is established
if connection.is_connected():
    print("Connected to the classicmodels database")

Connected to the classicmodels database